### ISSUE TITLE
shader-capture build error

### ISSUE THREAD

**Issue by diovudau** [p0nce/y4m-tools#4]
source/app.d(209,19): Error: function gfm.opengl.opengl.OpenGL.reload (GLVersion minVersion, GLVersion maxVersion) is not callable using argument types ()

**Comment by p0nce** [comment]
I don't really have time for this, I'm a taker for any PR.

**Comment by diovudau** [comment]
But can you tell me if that is one of your errors or did something in a library change it's API? That error doesn't look like a real pain to fix, I guess, if I assume knowledge of the D language and knowledge of that library. I don't have either.

**Comment by p0nce** [comment]
Should build now
